# Generated by Django 2.2.4 on 2019-09-20 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.utilities
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Названия')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описания')),
                ('image', models.ImageField(blank=True, upload_to=main.utilities.get_timestamp_path, verbose_name='Изображения')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is_Active')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотрый')),
                ('slug', models.SlugField(blank=True)),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-add_date'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='images/user.png', null=True, upload_to=main.utilities.get_timestamp_path, verbose_name='Аватар'),
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.BaseProduct')),
                ('floors_in_house', models.IntegerField(default=0, verbose_name='Этажы в доме')),
                ('floor', models.IntegerField(default=0, verbose_name='этаж')),
                ('number_rooms', models.IntegerField(default=1, verbose_name='Количество комнат')),
                ('total_area', models.IntegerField(default=1, verbose_name='Общая площадь')),
                ('rent_buy', models.BooleanField(default=True, verbose_name='Снять или Купить')),
            ],
            bases=('main.baseproduct',),
        ),
        migrations.CreateModel(
            name='Avtomobil',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.BaseProduct')),
                ('mark_model', models.CharField(choices=[('Audi', [(1, '100'), (2, '200'), (3, '80'), (4, '90'), (5, 'A1'), (6, 'A2'), (7, 'A3'), (8, 'A4'), (9, 'A4 Allroad Quattro'), (10, 'A7'), (11, 'A8'), (12, 'Cabriolet'), (13, 'Coupe'), (14, 'Q2'), (15, 'Q3'), (16, 'Q5'), (17, 'Quattro'), (18, 'R8'), (19, 'RS Q3'), (20, 'RS2'), (21, 'RS3'), (22, 'RS4'), (23, 'RS5'), (24, 'RS6'), (25, 'RS7'), (26, 'S1'), (27, 'S2'), (28, 'S3'), (29, 'S4'), (30, 'S5'), (3, 'S6'), (3, 'S7'), (3, 'S8'), (3, 'SQ5'), (3, 'SQ7'), (3, 'TT'), (3, 'TT RS'), (3, 'TTS'), (3, 'V8'), (3, 'other')])], max_length=10, verbose_name='Марка и модель')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новые или с пробегом')),
                ('year_issue', models.IntegerField(verbose_name='Год выпуска')),
                ('gear_shift', models.CharField(choices=[(1, 'mechanics'), (2, 'robot'), (3, 'automatic')], max_length=10, verbose_name='Коробка передач')),
                ('body_type', models.CharField(choices=[(1, 'sedan'), (2, 'hatchback'), (3, 'station_wagon'), (4, 'SUV'), (5, 'cabriolet'), (6, 'coupe'), (7, 'limousine'), (8, 'minivan'), (9, 'pickup'), (10, 'van'), (11, 'minibus')], max_length=10, verbose_name='Тип кузова')),
                ('engine_type', models.CharField(choices=[(1, 'petrol'), (2, 'diesel'), (3, 'hybrid'), (4, 'electro'), (5, 'gas')], max_length=10, verbose_name='Тип двигателя')),
                ('mileage', models.IntegerField(verbose_name='Пробег')),
                ('drive_unit', models.CharField(choices=[(1, 'front'), (2, 'full'), (3, 'rear')], max_length=10, verbose_name='Привод')),
                ('condition', models.BooleanField(default=True, verbose_name='Состояние')),
            ],
            bases=('main.baseproduct',),
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.BaseProduct')),
                ('house_area', models.IntegerField(default=1, verbose_name='Площадь дома')),
                ('land_area', models.IntegerField(default=1, verbose_name='Площадь участка')),
            ],
            bases=('main.baseproduct',),
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.BaseProduct')),
                ('land_area', models.IntegerField(default=1, verbose_name='Площадь')),
            ],
            bases=('main.baseproduct',),
        ),
        migrations.CreateModel(
            name='Second',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.BaseProduct')),
                ('second_hand', models.BooleanField(default=True, verbose_name='Новый или б/у')),
            ],
            bases=('main.baseproduct',),
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.BaseProduct')),
                ('schedule', models.CharField(choices=[(1, 'shift'), (2, 'part_time'), (3, 'full_time'), (4, 'free_schedule'), (5, 'shift_work'), (6, 'distant_work')], max_length=10, verbose_name='График работы')),
                ('work_experience', models.CharField(choices=[(1, 'not_matter'), (2, '1 year'), (3, '2 year'), (4, '3 year'), (5, '5 year'), (6, '10 year')], max_length=10, verbose_name='Опыть работы')),
            ],
            bases=('main.baseproduct',),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Категоры')),
                ('slug', models.SlugField(blank=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.Category')),
            ],
            options={
                'verbose_name': 'Categories',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad', to='main.Category'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='region',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad', to='main.Region'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad', to=settings.AUTH_USER_MODEL, verbose_name='Владелес'),
        ),
        migrations.CreateModel(
            name='AdditonalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.utilities.get_timestamp_path, verbose_name='Изображения')),
                ('baseproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.BaseProduct', verbose_name='Объявления')),
            ],
            options={
                'verbose_name': 'Дополнительная иллюстрация',
                'verbose_name_plural': 'Дополнительная иллюстрации',
            },
        ),
        migrations.CreateModel(
            name='Personals_clothes',
            fields=[
                ('second_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Second')),
                ('size', models.CharField(choices=[(1, '40-42(XS)'), (2, '42-44(S)'), (3, '44-46(M)'), (4, '46-48(L)'), (5, '48-50(XL)'), (6, '50-52(XXL)'), (7, '52-54(XXXL) and large')], max_length=10, verbose_name='Размер')),
            ],
            bases=('main.second',),
        ),
        migrations.CreateModel(
            name='Personals_shoes',
            fields=[
                ('second_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Second')),
                ('size', models.CharField(choices=[(1, '33'), (2, '34'), (3, '35'), (4, '36'), (5, '37'), (6, '38'), (7, '39'), (8, '40'), (9, '41'), (10, '42'), (11, '43'), (12, '44'), (13, '45'), (14, '46 and large')], max_length=10, verbose_name='Размер')),
            ],
            bases=('main.second',),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('vacancy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Vacancy')),
                ('gender', models.BooleanField(default=True, verbose_name='Пол')),
                ('age', models.IntegerField(verbose_name='Возраст')),
            ],
            bases=('main.vacancy',),
        ),
    ]
