# Generated by Django 2.2.5 on 2019-11-06 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='house_area',
            field=models.IntegerField(default=12, verbose_name='Площад Дома'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='additonalimage',
            name='baseproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.BaseProduct', verbose_name='Объявления'),
        ),
    ]
