# Generated by Django 2.2.5 on 2020-03-23 17:35

from django.db import migrations, models
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_avtomobil_ismileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.utilities.get_timestamp_path, verbose_name='Изображения'),
        ),
    ]
