# Generated by Django 2.2.5 on 2019-11-06 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191106_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='house_area',
        ),
    ]
