# Generated by Django 2.2.5 on 2020-03-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_baseproduct_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseproduct',
            name='image',
        ),
    ]
