# Generated by Django 2.2.5 on 2019-11-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_apartment_house_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avtomobil',
            name='mark_model',
            field=models.IntegerField(choices=[('Audi', [(1, '100'), (2, '200'), (3, '80'), (4, '90'), (5, 'A1'), (6, 'A2'), (7, 'A3'), (8, 'A4'), (9, 'A4 Allroad Quattro'), (10, 'A7'), (11, 'A8'), (12, 'Cabriolet'), (13, 'Coupe'), (14, 'Q2'), (15, 'Q3'), (16, 'Q5'), (17, 'Quattro'), (18, 'R8'), (19, 'RS Q3'), (20, 'RS2'), (21, 'RS3'), (22, 'RS4'), (23, 'RS5'), (24, 'RS6'), (25, 'RS7'), (26, 'S1'), (27, 'S2'), (28, 'S3'), (29, 'S4'), (30, 'S5'), (3, 'S6'), (3, 'S7'), (3, 'S8'), (3, 'SQ5'), (3, 'SQ7'), (3, 'TT'), (3, 'TT RS'), (3, 'TTS'), (3, 'V8'), (3, 'other')])], max_length=10, verbose_name='Марка и модель'),
        ),
    ]
