# Generated by Django 2.2.5 on 2020-03-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_baseproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproduct',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удаленный'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='number_rooms',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '>9'), (11, 'Студия')], verbose_name='Количество комнат'),
        ),
    ]
