# Generated by Django 2.2.5 on 2019-11-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191107_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avtomobil',
            name='body_type',
            field=models.IntegerField(choices=[(1, 'sedan'), (2, 'hatchback'), (3, 'station_wagon'), (4, 'SUV'), (5, 'cabriolet'), (6, 'coupe'), (7, 'limousine'), (8, 'minivan'), (9, 'pickup'), (10, 'van'), (11, 'minibus')], verbose_name='Тип кузова'),
        ),
        migrations.AlterField(
            model_name='avtomobil',
            name='drive_unit',
            field=models.IntegerField(choices=[(1, 'front'), (2, 'full'), (3, 'rear')], verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='avtomobil',
            name='engine_type',
            field=models.IntegerField(choices=[(1, 'petrol'), (2, 'diesel'), (3, 'hybrid'), (4, 'electro'), (5, 'gas')], verbose_name='Тип двигателя'),
        ),
        migrations.AlterField(
            model_name='avtomobil',
            name='gear_shift',
            field=models.IntegerField(choices=[(1, 'mechanics'), (2, 'robot'), (3, 'automatic')], verbose_name='Коробка передач'),
        ),
        migrations.AlterField(
            model_name='personals_clothes',
            name='size',
            field=models.IntegerField(choices=[(1, '40-42(XS)'), (2, '42-44(S)'), (3, '44-46(M)'), (4, '46-48(L)'), (5, '48-50(XL)'), (6, '50-52(XXL)'), (7, '52-54(XXXL) and large')], verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='personals_shoes',
            name='size',
            field=models.IntegerField(choices=[(1, '33'), (2, '34'), (3, '35'), (4, '36'), (5, '37'), (6, '38'), (7, '39'), (8, '40'), (9, '41'), (10, '42'), (11, '43'), (12, '44'), (13, '45'), (14, '46 and large')], verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='schedule',
            field=models.IntegerField(choices=[(1, 'shift'), (2, 'part_time'), (3, 'full_time'), (4, 'free_schedule'), (5, 'shift_work'), (6, 'distant_work')], verbose_name='График работы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='work_experience',
            field=models.IntegerField(choices=[(1, 'not_matter'), (2, '1 year'), (3, '2 year'), (4, '3 year'), (5, '5 year'), (6, '10 year')], verbose_name='Опыть работы'),
        ),
    ]
