# Generated by Django 2.2.5 on 2020-04-07 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200328_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avtomobil',
            old_name='isMileage',
            new_name='is_mileage',
        ),
    ]
