# Generated by Django 2.2.5 on 2020-04-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200407_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproduct',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотрый'),
        ),
    ]
