# Generated by Django 2.2.5 on 2019-11-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191107_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproduct',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
    ]
