# Generated by Django 2.2.5 on 2019-11-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191112_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avtomobil',
            name='body_type',
            field=models.IntegerField(choices=[(1, 'седан'), (2, 'хетчбэк'), (3, 'универсал'), (4, 'внедорожник'), (5, 'кабриолет'), (6, 'купе'), (7, 'лимузин'), (8, 'минивэн'), (9, 'пикап'), (10, 'фургон'), (11, 'микроавтобус')], verbose_name='Тип кузова'),
        ),
        migrations.AlterField(
            model_name='avtomobil',
            name='drive_unit',
            field=models.IntegerField(choices=[(1, 'передний'), (2, 'польный'), (3, 'задний')], verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='avtomobil',
            name='engine_type',
            field=models.IntegerField(choices=[(1, 'бензин'), (2, 'дизель'), (3, 'гибрид'), (4, 'электро'), (5, 'газ')], verbose_name='Тип двигателя'),
        ),
        migrations.AlterField(
            model_name='avtomobil',
            name='gear_shift',
            field=models.IntegerField(choices=[(1, 'механика'), (2, 'робот'), (3, 'автомат')], verbose_name='Коробка передач'),
        ),
        migrations.AlterField(
            model_name='avtomobil',
            name='mark_model',
            field=models.IntegerField(choices=[('Audi', [(1, '100'), (2, '200'), (3, '80'), (4, '90'), (5, 'A1'), (6, 'A2'), (7, 'A3'), (8, 'A4'), (9, 'A4 Allroad Quattro'), (10, 'A7'), (11, 'A8'), (12, 'Cabriolet'), (13, 'Coupe'), (14, 'Q2'), (15, 'Q3'), (16, 'Q5'), (17, 'Quattro'), (18, 'R8'), (19, 'RS Q3'), (20, 'RS2'), (21, 'RS3'), (22, 'RS4'), (23, 'RS5'), (24, 'RS6'), (25, 'RS7'), (26, 'S1'), (27, 'S2'), (28, 'S3'), (29, 'S4'), (30, 'S5'), (31, 'S6'), (32, 'S7'), (33, 'S8'), (34, 'SQ5'), (35, 'SQ7'), (36, 'TT'), (37, 'TT RS'), (38, 'TTS'), (39, 'V8'), (40, 'other')]), ('BMW', [(1, '1 серия'), (2, '1M')])], verbose_name='Марка и модель'),
        ),
        migrations.AlterField(
            model_name='personals_clothes',
            name='size',
            field=models.IntegerField(choices=[(1, '40-42(XS)'), (2, '42-44(S)'), (3, '44-46(M)'), (4, '46-48(L)'), (5, '48-50(XL)'), (6, '50-52(XXL)'), (7, '52-54(XXXL) и больше')], verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='personals_shoes',
            name='size',
            field=models.IntegerField(choices=[(1, '33'), (2, '34'), (3, '35'), (4, '36'), (5, '37'), (6, '38'), (7, '39'), (8, '40'), (9, '41'), (10, '42'), (11, '43'), (12, '44'), (13, '45'), (14, '46 и больше')], verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='schedule',
            field=models.IntegerField(choices=[(1, 'Вахтовый метод'), (2, 'Неполный день'), (3, 'Полный день'), (4, 'Свободный график'), (5, 'Сменный график'), (6, 'Удаленная работв')], verbose_name='График работы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='work_experience',
            field=models.IntegerField(choices=[(1, 'Не имеет значение'), (2, 'более 1 года'), (3, 'более 2 года'), (4, 'более 3 лет'), (5, 'более 5 лет'), (6, 'более 10 лет')], verbose_name='Опыть работы'),
        ),
    ]
