# Generated by Django 2.2.5 on 2019-11-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191119_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avtomobil',
            name='mark_model',
            field=models.IntegerField(choices=[('Audi', [(1, '100'), (2, '200'), (3, '80'), (4, '90'), (5, 'A1'), (6, 'A2'), (7, 'A3'), (8, 'A4'), (9, 'A4 Allroad Quattro'), (10, 'A7'), (11, 'A8'), (12, 'Cabriolet'), (13, 'Coupe'), (14, 'Q2'), (15, 'Q3'), (16, 'Q5'), (17, 'Quattro'), (18, 'R8'), (19, 'RS Q3'), (20, 'RS2'), (21, 'RS3'), (22, 'RS4'), (23, 'RS5'), (24, 'RS6'), (25, 'RS7'), (26, 'S1'), (27, 'S2'), (28, 'S3'), (29, 'S4'), (30, 'S5'), (31, 'S6'), (32, 'S7'), (33, 'S8'), (34, 'SQ5'), (35, 'SQ7'), (36, 'TT'), (37, 'TT RS'), (38, 'TTS'), (39, 'V8'), (40, 'other')]), ('BMW', [(41, '1 серия'), (42, '1M')])], verbose_name='Марка и модель'),
        ),
    ]
