# Generated by Django 2.2.5 on 2019-11-19 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191119_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avtomobil',
            name='is_new',
        ),
    ]
